### ISSUE TITLE
Accidentally bricked this keyboard with incorrect .bin

### ISSUE THREAD

**Issue by OnMyChown** [andypiper/rs40rgb-keeb#2]
Sorry if it's the wrong place to post. I haven't been able to get into DFU mode by holding escape anymore; are there pins I can bridge?
![20230827_171615](https://github.com/andypiper/rs40rgb-keeb/assets/80562023/6848994b-bde0-4e91-88e2-62e780b60c91)

**Comment by andypiper** [comment]
Sorry, I'm just a consumer of the same keyboard, unfortunately I know nothing about the hardware design here :-/
